# Generated by Django 2.0 on 2020-03-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('A', models.CharField(max_length=300)),
                ('B', models.CharField(max_length=300)),
                ('C', models.CharField(max_length=300)),
                ('D', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=5)),
            ],
        ),
    ]
