# Generated by Django 2.0 on 2020-03-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paperID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('paper_content', models.CharField(max_length=900, null=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('index', models.IntegerField()),
                ('paper_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gai.Userinfo'),
        ),
    ]
