# Generated by Django 2.0 on 2020-03-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gai', '0002_auto_20200314_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_content', models.TextField(max_length=10000)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='key_word',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='paperID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_content',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='paperID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gai.Paper'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gai.Userinfo'),
        ),
    ]
