# Generated by Django 2.0 on 2020-03-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gai', '0003_auto_20200314_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_content',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
