# Generated by Django 2.1.7 on 2020-03-17 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gai', '0004_auto_20200314_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='errorQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gai.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='paper_number',
        ),
        migrations.AddField(
            model_name='paper',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_content',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errorquestion',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gai.Userinfo'),
        ),
    ]
