# Generated by Django 2.1.7 on 2020-03-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gai', '0005_auto_20200317_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='A',
            new_name='answerA',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='B',
            new_name='answerB',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='C',
            new_name='answerC',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='D',
            new_name='answerD',
        ),
    ]
